version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    - echo "Running custom build commands" 
    - make html                            
python:
  version: 3.8
  install:
    - requirements: requirements.txt
